Page.delete_all

# products root
products = Page.create! name: "Products", content: "Product listing goes here."
Page.create! name: "Product Categories", content: "List of product categories goes here.", parent_id: products.id
Page.create! name: "Pricing", content: "Pricing information goes here.", parent_id: products.id
Page.create! name: "Shipping Info", content: "Shipping information goes here.", parent_id: products.id
Page.create! name: "International Shipping", content: "International shipping information goes here.", parent_id: products.id
Page.create! name: "Free Shipping Offer", content: "Free shipping offer goes here.", parent_id: products.id

#about root
about = Page.create! name: "About Us", content: "<p>Kid, I've flown from one side of this galaxy to the other. I've seen a lot of strange stuff, but I've never seen anything to make me believe there's one all-powerful Force controlling everything. There's no mystical energy field that controls my destiny. It's all a lot of simple tricks and nonsense. Oh God, my uncle. How am I ever gonna explain this? I care. So, what do you think of her, Han?</p> <p>I find your lack of faith disturbing. I'm surprised you had the courage to take the responsibility yourself. Don't be too proud of this technological terror you've constructed. The ability to destroy a planet is insignificant next to the power of the Force. She must have hidden the plans in the escape pod. Send a detachment down to retrieve them, and see to it personally, Commander. There'll be no one to stop us this time! Red Five standing by. Ye-ha!</p> <ul> <li>Ye-ha!</li> <li>No! Alderaan is peaceful. We have no weapons. You can't possibly&hellip;</li> <li>Still, she's got a lot of spirit. I don't know, what do you think?</li> </ul> <p>Don't underestimate the Force. I find your lack of faith disturbing. A tremor in the Force. The last time I felt it was in the presence of my old master. I call it luck. Oh God, my uncle. How am I ever gonna explain this?</p> <p>Look, I ain't in this for your revolution, and I'm not in it for you, Princess. I expect to be well paid. I'm in it for the money. The Force is strong with this one. I have you now. As you wish. I suggest you try it again, Luke. This time, let go your conscious self and act on instinct. Still, she's got a lot of spirit. I don't know, what do you think?</p> <ol> <li>Still, she's got a lot of spirit. I don't know, what do you think?</li> <li>Alderaan? I'm not going to Alderaan. I've got to go home. It's late, I'm in for it as it is.</li> </ol> <p>She must have hidden the plans in the escape pod. Send a detachment down to retrieve them, and see to it personally, Commander. There'll be no one to stop us this time! I'm trying not to, kid. The Force is strong with this one. I have you now. I find your lack of faith disturbing. You mean it controls your actions?</p>"
Page.create! name: "License Agreement", content: "<p>I hope I didn't brain my damage. Well, he's kind of had it in for me ever since I accidentally ran over his dog. Actually, replace 'accidentally' with 'repeatedly' and replace 'dog' with 'son.' Ahoy hoy?</p> <p>I don't like being outdoors, Smithers. For one thing, there's too many fat children. What's the point of going out? We're just going to wind up back here anyway. I didn't get rich by signing checks. They only come out in the night. Or in this case, the day.</p> <ul> <li>But, Aquaman, you cannot marry a woman without gills. You're from two different worlds&hellip; Oh, I've wasted my life.</li> <li>I'm a Spalding Gray in a Rick Dees world.</li> <li>How is education supposed to make me feel smarter? Besides, every time I learn something new, it pushes some old stuff out of my brain. Remember when I took that home winemaking course, and I forgot how to drive?</li> <li>Aaah! Natural light! Get it off me! Get it off me!</li> </ul> <p>Dad didn't leave&hellip; When he comes back from the store, he's going to wave those pop-tarts right in your face! He didn't give you gay, did he? Did he?! Can't you people take the law into your own hands? I mean, we can't be policing the entire city! And now, in the spirit of the season: start shopping. And for every dollar of Krusty merchandise you buy, I will be nice to a sick kid. For legal purposes, sick kids may include hookers with a cold. Hi. I'm Troy McClure. You may remember me from such self-help tapes as 'Smoke Yourself Thin' and 'Get Some Confidence, Stupid!' Old people don't need companionship. They need to be isolated and studied so it can be determined what nutrients they have that might be extracted for our personal use.</p> <p>I don't like being outdoors, Smithers. For one thing, there's too many fat children. Get ready, skanks! It's time for the truth train! Your guilty consciences may make you vote Democratic, but secretly you all yearn for a Republican president to lower taxes, brutalize criminals, and rule you like a king!</p> <ol> <li>And now, in the spirit of the season: start shopping. And for every dollar of Krusty merchandise you buy, I will be nice to a sick kid. For legal purposes, sick kids may include hookers with a cold.</li> <li>Brace yourselves gentlemen. According to the gas chromatograph, the secret ingredient is&hellip; Love!? Who's been screwing with this thing?</li> <li>We started out like Romeo and Juliet, but it ended up in tragedy.</li> </ol> <p>Get ready, skanks! It's time for the truth train! Son, a woman is like a beer. They smell good, they look good, you'd step over your own mother just to get one! But you can't stop at one. You wanna drink another woman! I didn't get rich by signing checks.</p>", parent_id: about.id
Page.create! name: "Privacy Policy", content: "Content of privacy policy.", parent_id: about.id
Page.create! name: "Contact Us", content: "Contact information goes here.", parent_id: about.id

#support root
Page.create! name: "Support", content: "<p>Well, how'd you become king, then? He hasn't got shit all over him. Be quiet! I don't want to talk to you no more, you empty-headed animal food trough water! I fart in your general direction! Your mother was a hamster and your father smelt of elderberries! Now leave before I am forced to taunt you a second time!</p> <p>How do you know she is a witch? But you are dressed as one&hellip; Well, we did do the nose. I have to push the pram a lot. I have to push the pram a lot.</p> <ul> <li>The Knights Who Say Ni demand a sacrifice!</li> <li>You can't expect to wield supreme power just 'cause some watery tart threw a sword at you!</li> <li>Did you dress her up like this?</li> </ul> <p>It's only a model. But you are dressed as one&hellip; She looks like one. You don't vote for kings. We want a shrubbery!! I'm not a witch.</p> <p>No, no, no! Yes, yes. A bit. But she's got a wart. On second thoughts, let's not go there. It is a silly place. Listen. Strange women lying in ponds distributing swords is no basis for a system of government. Supreme executive power derives from a mandate from the masses, not from some farcical aquatic ceremony. We shall say 'Ni' again to you, if you do not appease us.</p> <ol> <li>Oh! Come and see the violence inherent in the system! Help, help, I'm being repressed!</li> <li>We found them.</li> </ol> <p>I dunno. Must be a king. What do you mean? On second thoughts, let's not go there. It is a silly place. Look, my liege! Well, we did do the nose.</p>"
